[package]
edition = "2021"
name = "building_a_multithreaded_webserver"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "hello"
